enum class TokenType {
    //single character tokens
    LEFT_PAREN, RIGHT_PAREN,
    LEFT_BRACE, RIGHT_BRACE,
    COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,

    //one or two character tokens
    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,

    //literals
    IDENTIFIER, STRING, NUMBER,

    //keywords
    VAR, IF, VAL , ELSE, TRUE, FALSE, NIL, FOR, WHILE, PRINT, RETURN, THEN, END,

    // added to existing TokenType enum
    SCROLL, SEALSCROLL, RUNE_KW, INCANTATION, INVOKE, WHISPER, CONJURE, RELEASE, OMEN,
    SIGIL, ENDSIGIL, WITH, REQUIRES, ENACTS, WHILE_KW, PERSISTS, ENDQUEST,
    AND, OR, NAME, ELEMENT,


    EOF
}